### ISSUE TITLE
Brouillon illisible

### ISSUE THREAD

**Issue by rubRU** [rubRU/Enieme-FPS-pourri#1]
@nicolasSoares, Merci de remplir le trello avec les idées, je n'arrive pas à lire ton écriture.
Merci.

**Comment by romualdr** [comment]
TITS OR GTFO

**Comment by FloRest** [comment]
Pourquoi tu l'as appellé enieme-fps-pourri ?

**Comment by romualdr** [comment]
Parce qu'on comprends tous ce que c'est direct, lolz

**Comment by FloRest** [comment]
k, j'ai mis des trucs sur le trello

**Comment by FloRest** [comment]
Trello update, close.
